[package]
name = "c_plus"
version = "0.1.0"
authors = ["Matthew Bettcher <mattbettcher@gmail.com>"]

[build-dependencies] # <-- We added this and everything after!
lalrpop = "0.19.6"

[dependencies]
lalrpop-util = "0.19.6"
regex = "1"

